# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TemplateUpdateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemplateUpdateDialog(object):
    def setupUi(self, TemplateUpdateDialog):
        TemplateUpdateDialog.setObjectName("TemplateUpdateDialog")
        TemplateUpdateDialog.resize(980, 499)
        TemplateUpdateDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(TemplateUpdateDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(TemplateUpdateDialog)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setStyleSheet("image: url(:/images/icons/right-icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.labelCurrentTemplate = QtWidgets.QLabel(TemplateUpdateDialog)
        self.labelCurrentTemplate.setMinimumSize(QtCore.QSize(450, 300))
        self.labelCurrentTemplate.setText("")
        self.labelCurrentTemplate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentTemplate.setObjectName("labelCurrentTemplate")
        self.gridLayout.addWidget(self.labelCurrentTemplate, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonUpdate = QtWidgets.QPushButton(TemplateUpdateDialog)
        self.pushButtonUpdate.setMinimumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/refresh_icon.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"\n"
"}")
        self.pushButtonUpdate.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout.addWidget(self.pushButtonUpdate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonCancel = QtWidgets.QPushButton(TemplateUpdateDialog)
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/close_icon.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonCancel.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 3)
        self.labelNewTemplate = QtWidgets.QLabel(TemplateUpdateDialog)
        self.labelNewTemplate.setMinimumSize(QtCore.QSize(450, 300))
        self.labelNewTemplate.setText("")
        self.labelNewTemplate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNewTemplate.setObjectName("labelNewTemplate")
        self.gridLayout.addWidget(self.labelNewTemplate, 2, 2, 1, 1)
        self.labelAttention = QtWidgets.QLabel(TemplateUpdateDialog)
        self.labelAttention.setMinimumSize(QtCore.QSize(0, 70))
        self.labelAttention.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelAttention.setFont(font)
        self.labelAttention.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"")
        self.labelAttention.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAttention.setObjectName("labelAttention")
        self.gridLayout.addWidget(self.labelAttention, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(TemplateUpdateDialog)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(TemplateUpdateDialog)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)

        self.retranslateUi(TemplateUpdateDialog)
        QtCore.QMetaObject.connectSlotsByName(TemplateUpdateDialog)

    def retranslateUi(self, TemplateUpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        TemplateUpdateDialog.setWindowTitle(_translate("TemplateUpdateDialog", "TEMPLATE UPDATE"))
        self.pushButtonUpdate.setText(_translate("TemplateUpdateDialog", "YES - UPDATE"))
        self.pushButtonCancel.setText(_translate("TemplateUpdateDialog", "NO - CANCEL"))
        self.labelAttention.setText(_translate("TemplateUpdateDialog", "*"))
        self.label.setText(_translate("TemplateUpdateDialog", "CURRENT TEMPLATE"))
        self.label_3.setText(_translate("TemplateUpdateDialog", "NEW TEMPLATE"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TemplateUpdateDialog = QtWidgets.QDialog()
    ui = Ui_TemplateUpdateDialog()
    ui.setupUi(TemplateUpdateDialog)
    TemplateUpdateDialog.show()
    sys.exit(app.exec_())
